In [1]:
import numpy as np

In [2]:
d1 = np.array([24,34,34,56,])

In [3]:
d1.shape

(4,)

In [4]:
d1.size

4

In [5]:
d1(1)

TypeError: 'numpy.ndarray' object is not callable

In [6]:
d1[1]

34

In [7]:
d1[2]

34

In [8]:
d1[0:3]

array([24, 34, 34])

In [9]:
data=np.array(["appie","533","a",99.9])

In [10]:
data

array(['appie', '533', 'a', '99.9'], dtype='<U5')

In [11]:
import time 

start_time = time.time()
list1 =[x for x in range(1,1000000)]
list2 =[y for y in range(1,1000000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()

print("time taken by list concept",end_time-start_time)

NameError: name 'list2' is not defined

In [12]:
import time 

start_time = time.time()
list1 =[x for x in range(1,1000000)]
list2 =[y for y in range(1,1000000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()

print("time taken by list concept",end_time-start_time)

time taken by list concept 0.32477307319641113


In [13]:
import time

start_time1 = time.time()
arr1 = np.array(list1)
arr2 = np.arry(list2)

ar1*ar2

end_time1 = time.time()

print("time taken by numpy is:",end_time1-start_time)

AttributeError: module 'numpy' has no attribute 'arry'

In [14]:
import time

start_time1 = time.time()
arr1 = np.array(list1)
arr2 = np.arry(list2)

ar1*ar2

end_time1 = time.time()

print("time taken by numpy is:",end_time1-start_time)

AttributeError: module 'numpy' has no attribute 'arry'

In [15]:
import time

start_time1 = time.time()
ar1 = np.array(list1)
ar2 = np.arry(list2)

ar1*ar2

end_time1 = time.time()

print("Time taken by numpy is:",end_time1-start_time1)

AttributeError: module 'numpy' has no attribute 'arry'

In [16]:
import time

start_time1 = time.time()
ar1 = np.array(list1)
ar2 = np.array(list2)

ar1*ar2

end_time1 = time.time()

print("Time taken by numpy is:",end_time1-start_time1)

Time taken by numpy is: 0.18149495124816895


In [17]:
#2-d array declaration

d2 = np.array([[45,74,36],[96,87,69],[14,25,63]])

d2

array([[45, 74, 36],
       [96, 87, 69],
       [14, 25, 63]])

In [18]:
d2.shape

(3, 3)

In [19]:
d2.size

9

In [20]:
d2.ndim

2

In [21]:
d2


array([[45, 74, 36],
       [96, 87, 69],
       [14, 25, 63]])

In [22]:
d2[0]

array([45, 74, 36])

In [23]:
d2[0,2]

36

In [24]:
d1[0,1]

IndexError: too many indices for array

In [25]:
d2[0,2]

36

In [26]:
d2[1].max()

96

In [27]:
np.max(d2[1])

96

In [28]:
d2[:,2]

array([36, 69, 63])

In [29]:
d2[:,1].max()

87

In [30]:
d2[:,1].min()

25

In [31]:
d2[:,0].min()

14

In [32]:
d2[:,2].min()

36

In [33]:
d2[0].sum()

155

In [34]:
d2.sum()


509

In [35]:
d2.sum(axis=0)

array([155, 186, 168])

In [36]:
d2

array([[45, 74, 36],
       [96, 87, 69],
       [14, 25, 63]])

In [37]:
d2.sum(axis=1)

array([155, 252, 102])

In [38]:
d3 = np.array([[[1,2,3],4,5,6]],[[7,8,9],[10,11,12]]])

d3

SyntaxError: invalid syntax (<ipython-input-38-814b24c8e154>, line 1)

In [40]:
d3 = np.array([[[1,2,3],[4,5,6],[[7,8,9],[10,11,12]]])
               

d3

SyntaxError: invalid syntax (<ipython-input-40-5ec0e3d7d80d>, line 1)

In [41]:
d3 = np.array([[[1,2,3],[4,5,6],[[7,8,9],[10,11,12]]])
               

d3

SyntaxError: invalid syntax (<ipython-input-41-5ec0e3d7d80d>, line 1)

In [42]:
d3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

d3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
d3{0,0}

SyntaxError: invalid syntax (<ipython-input-43-dd91a1267023>, line 1)

In [45]:
range(1,10)

range(1, 10)

In [46]:
for i in range(1,11):
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 

In [47]:
for i  in arrange(1,20)
print(i, end = " ")

SyntaxError: invalid syntax (<ipython-input-47-1da52ffb274a>, line 1)

In [48]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [51]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [52]:
#zeos matrix
print(np.zeros([3,5]))


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
print(np.ones([10,20]))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [54]:
print(np.twnp.ios([20,90]))

AttributeError: module 'numpy' has no attribute 'twos'

In [55]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [57]:
d21 = np.array([[14,25,36,41,52],[24,51,35,15,16]])

d21

array([[14, 25, 36, 41, 52],
       [24, 51, 35, 15, 16]])

In [58]:
add_marks = np.tile(5,[4,5])

In [59]:
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [60]:
final_marks = d21+add_marks
final_marks

ValueError: operands could not be broadcast together with shapes (2,5) (4,5) 

In [61]:
mat = np.array([[1,10,30],[6,7,8,],[8,9,7]])
mat

array([[ 1, 10, 30],
       [ 6,  7,  8],
       [ 8,  9,  7]])

In [62]:
np.linalg.eig(mat)

(array([ 26.74506276, -11.29140433,  -0.45365843]),
 array([[-0.75076061, -0.93088547,  0.63349922],
        [-0.43097067,  0.16218783, -0.74272621],
        [-0.50062241,  0.32733371,  0.21687902]]))

In [63]:
np.linalg.inv(mat)

array([[-0.16788321,  1.45985401, -0.94890511],
       [ 0.16058394, -1.70072993,  1.25547445],
       [-0.01459854,  0.51824818, -0.38686131]])

In [64]:
np.random.random(10)

array([0.34310628, 0.78127819, 0.4464187 , 0.03321534, 0.19639551,
       0.03141501, 0.25300401, 0.90233743, 0.35359653, 0.18148252])

In [65]:
np.random.randint(10)

0

In [66]:
np.random.randint(10)

6

In [67]:
np.random.randint(10,20)

15

In [68]:
np.random.randint(10,20,30)

array([14, 16, 18, 17, 17, 11, 16, 14, 10, 10, 13, 12, 17, 11, 18, 10, 14,
       14, 14, 12, 18, 16, 11, 10, 13, 14, 12, 15, 19, 14])

In [69]:
np.random.rand(10)

array([0.23791496, 0.6941054 , 0.38181844, 0.24159513, 0.60291725,
       0.36069451, 0.30329422, 0.62565421, 0.67956345, 0.11414719])

In [70]:
np.arrange(1,13)

AttributeError: module 'numpy' has no attribute 'arrange'

In [71]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
np.arrange(4*3*4)

AttributeError: module 'numpy' has no attribute 'arrange'

In [75]:
np.arange(1,49).reshape(5,6,7)

ValueError: cannot reshape array of size 48 into shape (5,6,7)

In [76]:
np.arange(1,49).reshape(4,3,4)

ValueError: cannot reshape array of size 48 into shape (5,6,7)

In [77]:
2x2x3x3

SyntaxError: invalid syntax (<ipython-input-77-a69f4691bb15>, line 1)

In [78]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [ ]:
2x2x3x3